#%RAML 0.8
title: $NAME
version: 1.0.0
baseUri: /mobile/custom/$NAME
protocols: [HTTPS]
documentation:
 - title: Description
   content: |
     $DESCRIPTION
mediaType: "application/json"
/echo:
  displayName: echo
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "hello": "world"
              }
